name: ActionRelay
description: Provide a description here
author: Tiny_Murky

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  NAME_OF_THIS_JOB:
    description:
      'The *Name* of current Job, job name need to provided in order to stop
      waiting the job that run ActionRelay, which cause infinity loop'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub API Access Token'
    required: true
  TIMEOUT_AFTER_MINUTE:
    description:
      'timeout waiting progress after timeoutAfterMinute maximum is 15'
    required: false
    default: '15'
  INTERVAL_TO_CHECK_JOBS:
    description: 'how long of waiting to check if job complete in millisecond'
    required: false
    default: '2500'

outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
  post: dist/post.js
