import * as core from '@actions/core'
import Logger from '@/utils/logger.js'

/**
 * Info: (20250115 - Murky)
 * This can read env and change into class
 * might be delete later
 */
export class EnvConfig {
  readonly GITHUB_RUN_ATTEMPT: number

  constructor(env: Readonly<NodeJS.ProcessEnv>) {
    const { GITHUB_RUN_ATTEMPT: githubRunAttempt } = env

    if (!githubRunAttempt) {
      const errorMessage =
        'GITHUB_TOKEN is not generated by GITHUB Action or not provided'
      Logger.error(errorMessage)
      core.setFailed(errorMessage)
      throw new Error(errorMessage)
    }

    // Info: (20250114 - Murky) We can use ! because `core.setFailed` will end progress
    this.GITHUB_RUN_ATTEMPT = parseInt(githubRunAttempt, 10)
  }
}

const envConfigInstance = new EnvConfig(process.env)

export default envConfigInstance
